
<img src="../../img/ods_stickers.jpg">

## <center> [mlcourse.ai](https://mlcourse.ai) – открытый курс OpenDataScience по машинному обучению

Автор материала: Юрий Кашницкий (@yorko в Slack ODS). Материал распространяется на условиях лицензии [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Можно использовать в любых целях (редактировать, поправлять и брать за основу), кроме коммерческих, но с обязательным упоминанием автора материала.

# <center>Домашнее задание № 1 (демо).<br> Анализ данных по доходу населения UCI Adult</center>

**В задании предлагается с помощью Pandas ответить на несколько вопросов по данным репозитория UCI [Adult](https://archive.ics.uci.edu/ml/datasets/Adult) (качать данные не надо – они уже есть в репозитории). Для отправки решений используйте [онлайн-форму](https://docs.google.com/forms/d/1xAzU-5N6oEeR4UG8G44V6XL-Kbr4WYcPBG45Kijge2Y).**

Уникальные значения признаков (больше информации по ссылке выше):
- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

In [ ]:
import pandas as pd

In [ ]:
# data = pd.read_csv("../../data/adult.data.csv")
data = pd.read_csv('https://github.com/Yorko/mlcourse.ai/raw/main/data/adult.data.csv')
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Сколько мужчин и женщин (признак *sex*) представлено в этом наборе данных?**

In [82]:
# Ваш код здесь
data['sex'].shape[0]
data[data['sex'] == 'Female'].shape[0]

# data['sex'].value_counts()

10771

**2. Каков средний возраст (признак *age*) женщин?**

In [ ]:
# Ваш код здесь
data[data['sex'] == 'Female']['age'].mean()

36.85823043357163

**3. Какова доля граждан Германии (признак *native-country*)?**

In [ ]:
# Ваш код здесь
data[data['native-country'] == 'Germany'].shape[0] / data.shape[0] * 100

0.42074874850281013

**4-5. Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год? **

In [ ]:
# Ваш код здесь
print(data[data['salary'] == '>50K']['age'].mean(), data[data['salary'] == '>50K']['age'].std())
print(data[data['salary'] == '<=50K']['age'].mean(), data[data['salary'] == '<=50K']['age'].std())

44.24984058155847 10.519027719851826
36.78373786407767 14.02008849082488

**6. Правда ли, что люди, которые получают больше 50k, имеют как минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [ ]:
# Ваш код здесь
data[data['salary'] == '>50K']['education'].value_counts()

Bachelors       2221
HS-grad         1675
Some-college    1387
Masters          959
Prof-school      423
Assoc-voc        361
Doctorate        306
Assoc-acdm       265
10th              62
11th              60
7th-8th           40
12th              33
9th               27
5th-6th           16
1st-4th            6
Name: education, dtype: int64

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Amer-Indian-Eskimo*.**

In [ ]:
# Ваш код здесь
data[['age', 'race']].groupby(['race']).describe()
data[['age', 'sex']].groupby(['sex']).describe()

            age
          count       mean        std   min   25%   50%   75%   max
sex
Female  10771.0  36.858230  14.013697  17.0  25.0  35.0  46.0  90.0
Male    21790.0  39.433547  13.370630  17.0  29.0  38.0  48.0  90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [ ]:
# Ваш код здесь
import numpy as np

total = np.array(data[data['salary'] == '>50K']['marital-status'])
total = np.array(list(map(lambda x: x if 'Married' in x else pd.NaT, total)))

new_ser = pd.Series(total)
married = new_ser.dropna().shape[0]
non_married = len(total) - married
print(married / len(total) * 100, non_married / len(total) * 100)

# data[(data["sex"] == "Male")
#      & (data["marital-status"].str.startswith("Married"))][
#     "salary"
# ].value_counts(normalize=True)

# data[
#     (data["sex"] == "Male")
#     & ~(data["marital-status"].str.startswith("Married"))
# ]["salary"].value_counts(normalize=True)

85.9074097691621 14.092590230837903

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [ ]:
# Ваш код здесь
max_hours = data['hours-per-week'].max()
trudogolics = data[data['hours-per-week'] == 99].shape[0]
real_trudogolics = data[(data['hours-per-week'] == 99) & (data['salary'] == '>50K')].shape[0] / trudogolics * 100
print(max_hours, trudogolics, real_trudogolics)

99 85 29.411764705882355

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [ ]:
# Ваш код здесь
last = data[['hours-per-week', 'native-country', 'salary']]
less_money = last[last['salary'] == '<=50K'].drop(['salary'], axis=1)
more_money = last[last['salary'] == '>50K'].drop(['salary'], axis=1)
less_money.groupby(['native-country']).mean(), more_money.groupby(['native-country']).mean()

# for (country, salary), sub_df in data.groupby(["native-country", "salary"]):
#     print(country, salary, round(sub_df["hours-per-week"].mean(), 2))

# pd.crosstab(
#     data["native-country"],
#     data["salary"],
#     values=data["hours-per-week"],
#     aggfunc=np.mean,
# ).T

(                            hours-per-week
 native-country
 ?                                40.164760
 Cambodia                         41.416667
 Canada                           37.914634
 China                            37.381818
 Columbia                         38.684211
 Cuba                             37.985714
 Dominican-Republic               42.338235
 Ecuador                          38.041667
 El-Salvador                      36.030928
 England                          40.483333
 France                           41.058824
 Germany                          39.139785
 Greece                           41.809524
 Guatemala                        39.360656
 Haiti                            36.325000
 Holand-Netherlands               40.000000
 Honduras                         34.333333
 Hong                             39.142857
 Hungary                          31.300000
 India                            38.233333
 Iran                             41.440000
 Ireland                          40.947368
 Italy                            39.625000
 Jamaica                          38.239437
 Japan                            41.000000
 Laos                             40.375000
 Mexico                           40.003279
 Nicaragua                        36.093750
 Outlying-US(Guam-USVI-etc)       41.857143
 Peru                             35.068966
 Philippines                      38.065693
 Poland                           38.166667
 Portugal                         41.939394
 Puerto-Rico                      38.470588
 Scotland                         39.444444
 South                            40.156250
 Taiwan                           33.774194
 Thailand                         42.866667
 Trinadad&Tobago                  37.058824
 United-States                    38.799127
 Vietnam                          37.193548
 Yugoslavia                       41.600000,
                     hours-per-week
 native-country
 ?                        45.547945
 Cambodia                 40.000000
 Canada                   45.641026
 China                    38.900000
 Columbia                 50.000000
 Cuba                     42.440000
 Dominican-Republic       47.000000
 Ecuador                  48.750000
 El-Salvador              45.000000
 England                  44.533333
 France                   50.750000
 Germany                  44.977273
 Greece                   50.625000
 Guatemala                36.666667
 Haiti                    42.750000
 Honduras                 60.000000
 Hong                     45.000000
 Hungary                  50.000000
 India                    46.475000
 Iran                     47.500000
 Ireland                  48.000000
 Italy                    45.400000
 Jamaica                  41.100000
 Japan                    47.958333
 Laos                     40.000000
 Mexico                   46.575758
 Nicaragua                37.500000
 Peru                     40.000000
 Philippines              43.032787
 Poland                   39.000000
 Portugal                 41.500000
 Puerto-Rico              39.416667
 Scotland                 46.666667
 South                    51.437500
 Taiwan                   46.800000
 Thailand                 58.333333
 Trinadad&Tobago          40.000000
 United-States            45.505369
 Vietnam                  39.200000
 Yugoslavia               49.500000)